### ISSUE TITLE
Failed to open the added source

### ISSUE THREAD

**Issue by demanuPL** [thilojaeggi/WinGetty#39]
Winget refuses to add wingetty source, returns:
`Failed to open the added source.`

the same behaviour with --verbose option, no additional information

winget source add -n WinGetty -t "Microsoft.Rest" -a https://wingetty.mylab.lab/wg/

I've enabled TLS 1.2 and SSL 3.0 in internet settings but it didn't fix it

**Comment by excelsi** [comment]
I have this issue too after finally conguring Nginx correctly:
![image](https://github.com/thilojaeggi/WinGetty/assets/8747559/b6623f0d-385c-4410-af53-c13d7980c3a7)
And the Setup Command looks fine too:
![image](https://github.com/thilojaeggi/WinGetty/assets/8747559/5c7b3eee-5d1d-4c8b-b291-7d7487628d0c)
It is Version 0.0.9

In a previous release this already worked for me.
Thanks!

**Comment by rileyz** [comment]
This might or might not be helpful.

If its being an ass, you can try and hack in the entry for wingetty.  The winget conf is located in the path below.
`C:\Users\<username>\AppData\Local\Microsoft\WinGet\Settings\defaultState`

The config looks like this
```
Sources:
- Name: msstore
  Type:
  Arg:
  Data:
  Identifier:
  IsTombstone: true
- Name: winget
  Type:
  Arg:
  Data:
  Identifier:
  IsTombstone: true
- Name: WinGetty
  Type: Microsoft.Rest
  Arg: https://addyourwingettyinstancehere.com/wg/
  Data:
  Identifier: WinGetty
  IsTombstone: false
```

If you _happen_ to be using WinGetUI, I found I had to use the bundled winget that came with it. Which is stored in path below, change directory to dir and execute your command to add the repo, or explicitly use/target the executable.
`"C:\Program Files\WingetUI\wingetui\PackageEngine\Managers\winget-cli_x64\"`
